// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHFp5T0o1UHV-B82xK8_I6uhfQ7qyHGY',
    appId: '1:453980349317:web:ea03b0730b32fdbd779aec',
    messagingSenderId: '453980349317',
    projectId: 'faso-yango',
    authDomain: 'faso-yango.firebaseapp.com',
    storageBucket: 'faso-yango.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWAZEDMqW_l-d9NIjbVJu7j2hbToev9Y',
    appId: '1:453980349317:android:7e6981587eb3d76f779aec',
    messagingSenderId: '453980349317',
    projectId: 'faso-yango',
    storageBucket: 'faso-yango.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDo4yFHgTESgTIFWH9u2mWlmWHzmPMcQ',
    appId: '1:453980349317:ios:bb688091495f902a779aec',
    messagingSenderId: '453980349317',
    projectId: 'faso-yango',
    storageBucket: 'faso-yango.appspot.com',
    iosBundleId: 'com.example.yangoFaso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDo4yFHgTESgTIFWH9u2mWlmWHzmPMcQ',
    appId: '1:453980349317:ios:bb688091495f902a779aec',
    messagingSenderId: '453980349317',
    projectId: 'faso-yango',
    storageBucket: 'faso-yango.appspot.com',
    iosBundleId: 'com.example.yangoFaso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHFp5T0o1UHV-B82xK8_I6uhfQ7qyHGY',
    appId: '1:453980349317:web:0c929c34a5852cd1779aec',
    messagingSenderId: '453980349317',
    projectId: 'faso-yango',
    authDomain: 'faso-yango.firebaseapp.com',
    storageBucket: 'faso-yango.appspot.com',
  );
}
